### ISSUE TITLE
pdo-oci extension not installed

### ISSUE THREAD

**Issue by sangio90** [caffeinalab/php-fpm-oci8#1]
Hello and thank you for this Dockerfile.

I tried it and the instantclient part works fine, still I wasn't able to use PHP to interact with instantclient and connect to an Oracle database.
I noticed in the phpinfo() that pdo_oci isn't installed.

I got it working extending your image in this way:

```
FROM caffeina/php-fpm-oci8

RUN wget http://php.net/distributions/php-7.1.6.tar.gz \
    mkdir php_oci \
    mv php-7.1.6.tar.gz ./php_oci

WORKDIR php_oci

RUN tar xfvz php-7.1.6.tar.gz

WORKDIR php-7.1.6/ext/pdo_oci

RUN phpize \
    ./configure --with-pdo-oci=instantclient,/usr/local/instantclient,12.1 \
    make \
    make install \
    echo extension=pdo_oci.so > /usr/local/etc/php/conf.d/pdo_oci.ini \
    php -v
```

Would you consider accepting a PR if I modify your Dockerfile to add pdo extension or is it beyond the scope of this Dockerfile? (in that case, how do you connect to Oracle?)

Thanks

**Comment by lastguest** [comment]
> Would you consider accepting a PR 

Please. :)
